version: '3.8'
services:
  app:
    build: .
    container_name: bookies-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookies
      - JWT_SECRET=bookiessecretkey123
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: bookies-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
